<?php
/**
 * Cookie consent for vettepoeder.nl.
 */
declare(strict_types=1);
if (!defined('ABSPATH')) { exit; }
const SITE_COOKIE_CONSENT = 'site_cookie_consent';
add_filter('wp_get_consent_type', static fn (): string => 'optin');
function site_cookie_policy_url(): string { return function_exists('pll_current_language') && pll_current_language('slug') === 'en' ? home_url('/en/privacy-cookies/') : home_url('/privacy-cookies/'); }
add_action('wp_footer', static function (): void { if (is_admin()) return; ?>
<style>.site-cookie-banner[hidden],.site-cookie-modal[hidden]{display:none!important}.site-cookie-banner{position:fixed;z-index:99998;left:50%;bottom:18px;transform:translateX(-50%);width:min(1040px,calc(100% - 28px));background:#071424;color:#fff;border:1px solid #38506d;border-radius:16px;box-shadow:0 18px 60px rgba(0,0,0,.35);padding:18px}.site-cookie-inner{display:grid;grid-template-columns:1fr auto;gap:18px;align-items:center}.site-cookie-banner h2{font-size:1.15rem;margin:0 0 6px;color:#fff}.site-cookie-banner p{margin:0;color:#d7e1ee;font-size:.95rem;line-height:1.5}.site-cookie-actions{display:flex;gap:9px;flex-wrap:wrap;justify-content:flex-end}.site-cookie-button{border:1px solid #ff7a24;border-radius:10px;background:#ff7a24;color:#111827;cursor:pointer;font:inherit;font-weight:850;padding:11px 14px}.site-cookie-button.secondary{background:transparent;color:#fff;border-color:#516984}.site-cookie-settings-link{background:transparent;border:0;color:inherit;text-decoration:underline;cursor:pointer;font:inherit;padding:0}@media(max-width:760px){.site-cookie-inner{grid-template-columns:1fr}.site-cookie-actions{display:grid;grid-template-columns:1fr}}</style>
<section class="site-cookie-banner" id="site-cookie-banner" role="dialog" aria-labelledby="site-cookie-title" hidden><div class="site-cookie-inner"><div><h2 id="site-cookie-title">Cookievoorkeuren</h2><p>We gebruiken noodzakelijke cookies voor een veilige website. Statistieken en externe inhoud blijven uit tenzij je toestemming geeft. <a href="<?php echo esc_url(site_cookie_policy_url()); ?>">Lees meer</a>.</p></div><div class="site-cookie-actions"><button class="site-cookie-button secondary" data-cookie-choice="necessary">Alleen noodzakelijk</button><button class="site-cookie-button" data-cookie-choice="all">Alles toestaan</button></div></div></section>
<script>(()=>{const name='site_cookie_consent';const banner=document.getElementById('site-cookie-banner');const has=()=>document.cookie.split('; ').some(c=>c.startsWith(name+'='));const set=v=>{document.cookie=name+'='+encodeURIComponent(JSON.stringify(v))+'; Max-Age=15552000; Path=/; SameSite=Lax'+(location.protocol==='https:'?'; Secure':'');banner.hidden=true;window.dispatchEvent(new CustomEvent('site-cookie-consent',{detail:v}));};if(!has())banner.hidden=false;document.addEventListener('click',e=>{const b=e.target.closest('[data-cookie-choice]');if(!b)return;set({necessary:true,statistics:b.dataset.cookieChoice==='all',external:b.dataset.cookieChoice==='all',version:1});});})();</script>
<?php });
